'use client';

import { useState, useEffect } from 'react';
import DashboardLayout from '../components/DashboardLayout';
import { FileText, Users, GitCompare, Loader2, CheckCircle2, AlertCircle, Sparkles } from 'lucide-react';
import { api } from '../utils/api';

export default function SynthesisPage() {
    const [patients, setPatients] = useState<any[]>([]);
    const [selectedPatients, setSelectedPatients] = useState<string[]>([]);
    const [activeTab, setActiveTab] = useState<'summary' | 'compare'>('summary');
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);

    // Fetch patients on mount
    useEffect(() => {
        const fetchPatients = async () => {
            try {
                const response = await api.getPatients();
                setPatients(response.patients || []);
            } catch (error) {
                // Silently use mock data as fallback when backend is unavailable
                // Scenario: Dr. Martin treats 2 patients with same chronic pathology
                // New treatment implemented 3 months ago shows different results per patient profile
                setPatients([
                    {
                        id: 'PAT-A-2024',
                        name: 'Patient A',
                        age: 58,
                        gender: 'Male',
                        document_count: 67,
                        diagnosis: 'Chronic Heart Failure',
                        treatment_start: '2024-10-01',
                        profile: 'Diabetic, Hypertensive'
                    },
                    {
                        id: 'PAT-B-2024',
                        name: 'Patient B',
                        age: 52,
                        gender: 'Female',
                        document_count: 73,
                        diagnosis: 'Chronic Heart Failure',
                        treatment_start: '2024-10-01',
                        profile: 'Non-diabetic, Controlled BP'
                    },
                    {
                        id: 'PAT003',
                        name: 'Maria Garcia',
                        age: 38,
                        gender: 'Female',
                        document_count: 15,
                        diagnosis: 'Asthma',
                        treatment_start: '2023-05-12'
                    },
                    {
                        id: 'PAT004',
                        name: 'Ahmed Hassan',
                        age: 51,
                        gender: 'Male',
                        document_count: 22,
                        diagnosis: 'Hypertension',
                        treatment_start: '2022-11-20'
                    }
                ]);
            }
        };
        fetchPatients();
    }, []);

    const handlePatientSelection = (patientId: string) => {
        setSelectedPatients(prev => {
            if (prev.includes(patientId)) {
                return prev.filter(id => id !== patientId);
            }
            // Limit to 5 patients for comparison
            if (activeTab === 'compare' && prev.length >= 5) {
                return prev;
            }
            // Only 1 patient for summary
            if (activeTab === 'summary') {
                return [patientId];
            }
            return [...prev, patientId];
        });
    };

    const handleGenerateSummary = async () => {
        if (selectedPatients.length === 0) {
            setError('Please select a patient');
            return;
        }

        setLoading(true);
        setError(null);
        setResult(null);

        try {
            const response = await api.generateSummary(selectedPatients[0]);
            setResult(response);
        } catch (err: any) {
            // Show mock data if service is unavailable
            const patient = patients.find(p => p.id === selectedPatients[0]);
            const isPatientA = selectedPatients[0] === 'PAT-A-2024';
            const isPatientB = selectedPatients[0] === 'PAT-B-2024';

            setTimeout(() => {
                if (isPatientA || isPatientB) {
                    // Professional medical summary for Dr. Martin's patients
                    setResult({
                        report_id: `REPORT-${Date.now()}`,
                        report_type: 'patient_summary',
                        synthesis_text: `PATIENT SUMMARY - ${patient?.name} (${selectedPatients[0]})
Generated by: Dr. Martin's Clinical Team
Date: ${new Date().toLocaleDateString('fr-FR')}

═══════════════════════════════════════════════════════════════

PATIENT PROFILE:
- ID: ${selectedPatients[0]}
- Age: ${patient?.age} years
- Gender: ${patient?.gender}
- Diagnosis: ${(patient as any)?.diagnosis || 'N/A'}
- Clinical Profile: ${(patient as any)?.profile || 'N/A'}
- Treatment Start: ${(patient as any)?.treatment_start || 'N/A'}
- Total Documents Analyzed: ${patient?.document_count || 0} (hospital reports, blood tests, prescriptions)

TREATMENT TIMELINE:
New treatment protocol initiated 3 months ago (October 2024) for chronic heart failure management.

DOCUMENTED EVIDENCE (${patient?.document_count} documents):
✓ ${Math.floor((patient?.document_count || 0) * 0.4)} Hospital admission reports
✓ ${Math.floor((patient?.document_count || 0) * 0.35)} Laboratory blood test results
✓ ${Math.floor((patient?.document_count || 0) * 0.15)} Prescription records
✓ ${Math.floor((patient?.document_count || 0) * 0.10)} Follow-up consultation notes

${isPatientA ? `TREATMENT RESPONSE - PATIENT A:
▸ MODERATE IMPROVEMENT observed
▸ Ejection fraction: Baseline 35% → Current 42% (+7%)
▸ NT-proBNP levels: Reduced by 28% over 3 months
▸ 6-minute walk test: Improved from 280m to 340m
▸ NYHA Classification: Class III → Class II-III (borderline)

COMPLICATING FACTORS:
⚠ Diabetes Type 2 affecting recovery rate
⚠ Hypertension requires dual medication
⚠ Medication adherence: 85% (room for improvement)

KEY OBSERVATIONS:
• Response slower than expected due to diabetic profile
• Blood sugar control impacts treatment efficacy
• Requires closer monitoring and dosage adjustments
• Consider adding SGLT2 inhibitor for dual benefit` : ''}

${isPatientB ? `TREATMENT RESPONSE - PATIENT B:
▸ EXCELLENT IMPROVEMENT observed
▸ Ejection fraction: Baseline 33% → Current 48% (+15%)
▸ NT-proBNP levels: Reduced by 52% over 3 months
▸ 6-minute walk test: Improved from 290m to 420m
▸ NYHA Classification: Class III → Class I-II

FAVORABLE FACTORS:
✓ Non-diabetic status enables optimal response
✓ Well-controlled blood pressure
✓ Medication adherence: 97% (excellent)
✓ Active lifestyle modifications maintained

KEY OBSERVATIONS:
• Response exceeds typical treatment outcomes
• Patient profile ideal for this treatment protocol
• Minimal side effects reported
• Could serve as reference case for similar profiles` : ''}

RECOMMENDATIONS:
${isPatientA ? `1. Adjust medication dosing considering diabetic profile
2. Implement stricter glucose monitoring protocol
3. Consider combination therapy adjustment
4. Increase follow-up frequency to bi-weekly
5. Dietary consultation for optimal glycemic control` : ''}

${isPatientB ? `1. Continue current treatment protocol
2. Maintain monthly monitoring schedule
3. Gradual exercise intensity increase permitted
4. Document as successful case study
5. Standard follow-up at 6-month mark` : ''}

NEXT STEPS:
- Comparative analysis with Patient ${isPatientA ? 'B' : 'A'} recommended
- Re-evaluate treatment efficacy at 6-month mark
- Continue documenting all clinical parameters

═══════════════════════════════════════════════════════════════
Note: This is demonstration data. Start synthese-comparative service (port 8005) for real AI analysis.`,
                        key_findings: {
                            documents_analyzed: patient?.document_count || 0,
                            patient_id: selectedPatients[0],
                            treatment_duration_months: 3,
                            response_category: isPatientA ? 'moderate' : 'excellent',
                            generated_at: new Date().toISOString(),
                            status: 'mock_data_professional'
                        }
                    });
                } else {
                    // Standard summary for other patients
                    setResult({
                        report_id: `REPORT-${Date.now()}`,
                        report_type: 'patient_summary',
                        synthesis_text: `PATIENT SUMMARY - ${patient?.name || 'Unknown Patient'} (${selectedPatients[0]})\n\nPATIENT INFORMATION:\n- Patient ID: ${selectedPatients[0]}\n- Age: ${patient?.age || 'N/A'} years\n- Gender: ${patient?.gender || 'N/A'}\n- Total Documents: ${patient?.document_count || 0}\n\nMEDICAL OVERVIEW:\nThe patient has ${patient?.document_count || 0} medical documents on file under continuous observation.\n\nNote: This is demonstration data. Start synthese-comparative service (port 8005) for AI analysis.`,
                        key_findings: {
                            documents_analyzed: patient?.document_count || 0,
                            patient_id: selectedPatients[0],
                            generated_at: new Date().toISOString(),
                            status: 'mock_data'
                        }
                    });
                }
                setLoading(false);
            }, 1500);
        }
    };

    const handleComparePatients = async () => {
        if (selectedPatients.length < 2) {
            setError('Please select at least 2 patients to compare');
            return;
        }

        setLoading(true);
        setError(null);
        setResult(null);

        try {
            const response = await api.comparePatients(selectedPatients);
            setResult(response);
        } catch (err: any) {
            // Show mock data if service is unavailable
            const selectedPatientsData = patients.filter(p => selectedPatients.includes(p.id));
            const hasPatientA = selectedPatients.includes('PAT-A-2024');
            const hasPatientB = selectedPatients.includes('PAT-B-2024');
            const isClinicalComparison = hasPatientA && hasPatientB;

            setTimeout(() => {
                if (isClinicalComparison) {
                    // Dr. Martin's comparative analysis
                    setResult({
                        report_id: `COMPARISON-${Date.now()}`,
                        report_type: 'comparative_clinical_analysis',
                        synthesis_text: `COMPARATIVE CLINICAL ANALYSIS
Dr. Martin's Treatment Response Study
Same Chronic Pathology - Different Patient Profiles

═══════════════════════════════════════════════════════════════

STUDY CONTEXT:
Both Patient A and Patient B suffer from the same chronic heart failure pathology.
New treatment protocol initiated 3 months ago (October 2024).
Clinical question: Does patient profile affect treatment response?

PATIENTS COMPARED:
1. Patient A (PAT-A-2024) - Age 58, Male, 67 documents
   Profile: Diabetic, Hypertensive
   
2. Patient B (PAT-B-2024) - Age 52, Female, 73 documents
   Profile: Non-diabetic, Controlled BP

TOTAL DOCUMENTATION ANALYZED: 140 documents
- Hospital reports: 56 documents
- Blood test results: 49 documents  
- Prescription records: 21 documents
- Consultation notes: 14 documents

═══════════════════════════════════════════════════════════════

COMPARATIVE TREATMENT OUTCOMES (3-Month Follow-up):

┌─────────────────────────┬──────────────┬──────────────┬────────────┐
│ Clinical Parameter      │  Patient A   │  Patient B   │ Difference │
├─────────────────────────┼──────────────┼──────────────┼────────────┤
│ Ejection Fraction Δ     │    +7%       │    +15%      │   +8% (B)  │
│ NT-proBNP Reduction     │    -28%      │    -52%      │  -24% (B)  │
│ 6-Min Walk Test Δ       │   +60m       │   +130m      │  +70m (B)  │
│ NYHA Class Change       │  III→II-III  │   III→I-II   │  Better(B) │
│ Med. Adherence Rate     │    85%       │    97%       │  +12% (B)  │
└─────────────────────────┴──────────────┴──────────────┴────────────┘

KEY COMPARATIVE FINDINGS:

🔍 TREATMENT EFFICACY:
▸ Patient B shows 86% better ejection fraction improvement
▸ Patient B exhibits nearly 2x reduction in cardiac biomarkers
▸ Walking capacity improvement 2.2x greater in Patient B
▸ Both patients improved, but response magnitude differs significantly

⚠️ PROFILE-DEPENDENT FACTORS:

PATIENT A (Slower Response):
❌ Diabetes Type 2 reduces treatment efficacy by ~40%
❌ Hypertension requires dual therapy, potential drug interactions
❌ Medication adherence 12% lower
❌ Inflammatory markers remain elevated (diabetic profile)
✓ Still shows positive trend, needs longer observation period

PATIENT B (Optimal Response):  
✓ Non-diabetic metabolism enables full drug efficacy
✓ Controlled blood pressure - no competing medications
✓ Excellent adherence due to minimal side effects
✓ Lifestyle modifications better tolerated
✓ Response aligns with clinical trial expectations

═══════════════════════════════════════════════════════════════

STATISTICAL ANALYSIS:
• Response differential: 73% attributable to patient profile
• Diabetic status impact: -35% to -45% treatment efficacy
• Age factor: Minimal (6 years difference not significant)
• Gender factor: Not conclusive with current data
• Document correlation: Quality > Quantity (73 vs 67 docs)

CLINICAL INTERPRETATION:

This comparative analysis reveals that the NEW TREATMENT PROTOCOL 
demonstrates PROFILE-DEPENDENT EFFICACY:

1. NON-DIABETIC PATIENTS (like Patient B):
   • Excellent response expected within 3 months
   • Standard protocol sufficient
   • Optimal candidates for this treatment

2. DIABETIC PATIENTS (like Patient A):
   • Modified expectations needed (6-9 months for optimal results)
   • Requires protocol adjustment:
     → Higher dosing consideration
     → Additional glycemic control
     → Combined SGLT2 inhibitor therapy
     → More frequent monitoring

═══════════════════════════════════════════════════════════════

RECOMMENDATIONS:

FOR PATIENT A:
1. ⚕️ Adjust treatment dosing (+20% consideration)
2. 📊 Implement strict glucose monitoring (HbA1c target <7%)
3. 💊 Consider adding SGLT2 inhibitor (dual benefit: cardiac + glycemic)
4. 🔄 Increase follow-up to bi-weekly for 2 months
5. 📆 Re-evaluate at 6-month mark (realistic timeline for diabetic patients)

FOR PATIENT B:
1. ✅ Continue current protocol (proven effective)
2. 📅 Maintain standard monthly monitoring
3. 📈 Document as reference case for non-diabetic CHF patients
4. 💪 Gradually increase exercise intensity
5. 📋 Schedule 6-month comprehensive re-assessment

PROTOCOL ADJUSTMENTS NEEDED:
• Create separate treatment pathways based on diabetic status
• Develop predictive model for response based on patient profile
• Update clinical guidelines to reflect profile-dependent outcomes
• Consider this data for future patient stratification

═══════════════════════════════════════════════════════════════

CONCLUSION:
The same treatment yields SIGNIFICANTLY DIFFERENT RESULTS depending 
on patient metabolic profile. This validates the need for 
PERSONALIZED MEDICINE approaches in chronic heart failure management.

Dr. Martin's hypothesis CONFIRMED: Patient profile critically 
determines treatment response timeline and magnitude.

Next Steps:
→ Expand study to larger patient cohort
→ Implement profile-based treatment protocols
→ Continue monitoring both patients
→ Publish findings for clinical community

═══════════════════════════════════════════════════════════════
Generated: ${new Date().toLocaleString('fr-FR')}
Note: This is professional demonstration data. Start synthese-comparative 
service (port 8005) for real AI-powered comparative analysis.`,
                        key_findings: {
                            patients_compared: 2,
                            patient_ids: ['PAT-A-2024', 'PAT-B-2024'],
                            total_documents: 140,
                            treatment_duration_months: 3,
                            key_finding: 'Profile-dependent treatment response confirmed',
                            efficacy_differential: '73%',
                            generated_at: new Date().toISOString(),
                            status: 'mock_clinical_study'
                        }
                    });
                } else {
                    // Standard comparison
                    setResult({
                        report_id: `COMPARISON-${Date.now()}`,
                        report_type: 'comparison',
                        synthesis_text: `COMPARATIVE ANALYSIS - ${selectedPatients.length} Patients\n\nPATIENTS ANALYZED:\n${selectedPatientsData.map((p, i) => `${i + 1}. ${p.name} (${p.id}) - Age ${p.age}, ${p.gender}, ${p.document_count} documents`).join('\n')}\n\nCOMPARATIVE OVERVIEW:\n• Total documents: ${selectedPatientsData.reduce((sum, p) => sum + (p.document_count || 0), 0)}\n• Average age: ${Math.round(selectedPatientsData.reduce((sum, p) => sum + (p.age || 0), 0) / selectedPatientsData.length)} years\n\nNote: This is demonstration data. Start synthese-comparative service (port 8005) for real analysis.`,
                        key_findings: {
                            patients_compared: selectedPatients.length,
                            patient_ids: selectedPatients,
                            total_documents: selectedPatientsData.reduce((sum, p) => sum + (p.document_count || 0), 0),
                            generated_at: new Date().toISOString(),
                            status: 'mock_data'
                        }
                    });
                }
                setLoading(false);
            }, 2000);
        }
    };

    const resetSelection = () => {
        setSelectedPatients([]);
        setResult(null);
        setError(null);
    };

    return (
        <DashboardLayout>
            <div className="space-y-6">
                {/* Header - MEDICAL THEME */}
                <div className="relative gradient-teal rounded-3xl p-8 text-white shadow-lg overflow-hidden">
                    {/* Animated Background */}
                    <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-white/10 rounded-full blur-3xl animate-pulse-soft"></div>
                    <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-96 h-96 bg-white/5 rounded-full blur-3xl"></div>

                    <div className="relative z-10">
                        <div className="flex items-center space-x-4">
                            <div className="w-16 h-16 bg-white/20 backdrop-blur-lg rounded-2xl flex items-center justify-center border border-white/30 shadow-lg">
                                <GitCompare className="h-8 w-8 text-white" />
                            </div>
                            <div>
                                <h1 className="text-3xl font-bold mb-1">Comparative Analysis</h1>
                                <p className="text-white/90 text-base">AI-Powered Patient Synthesis & Comparison</p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Tab Navigation - Medical Theme */}
                <div className="medical-card p-2 inline-flex space-x-2">
                    <button
                        onClick={() => { setActiveTab('summary'); resetSelection(); }}
                        className={`px-6 py-3 rounded-xl font-semibold transition-all flex items-center space-x-2 ${activeTab === 'summary'
                            ? 'bg-teal-500 text-white shadow-md shadow-teal-500/30'
                            : 'text-gray-600 hover:bg-teal-50'
                            }`}
                    >
                        <FileText className="h-5 w-5" />
                        <span>Patient Summary</span>
                    </button>
                    <button
                        onClick={() => { setActiveTab('compare'); resetSelection(); }}
                        className={`px-6 py-3 rounded-xl font-semibold transition-all flex items-center space-x-2 ${activeTab === 'compare'
                            ? 'bg-teal-500 text-white shadow-md shadow-teal-500/30'
                            : 'text-gray-600 hover:bg-teal-50'
                            }`}
                    >
                        <Users className="h-5 w-5" />
                        <span>Compare Patients</span>
                    </button>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    {/* Left Panel - Patient Selection */}
                    <div className="medical-card p-6">
                        <div className="flex items-center justify-between mb-4">
                            <h2 className="text-xl font-bold text-gray-900 flex items-center">
                                <div className="w-8 h-8 bg-teal-100 rounded-lg flex items-center justify-center mr-2">
                                    <Users className="h-4 w-4 text-teal-600" />
                                </div>
                                {activeTab === 'summary' ? 'Select Patient' : 'Select Patients to Compare'}
                            </h2>
                            {selectedPatients.length > 0 && (
                                <button
                                    onClick={resetSelection}
                                    className="text-sm text-teal-600 hover:text-teal-700 font-semibold"
                                >
                                    Clear ({selectedPatients.length})
                                </button>
                            )}
                        </div>

                        {activeTab === 'compare' && (
                            <div className="mb-4 p-3 bg-teal-50 rounded-xl border border-teal-100">
                                <p className="text-sm text-teal-700 font-medium">
                                    <Sparkles className="h-4 w-4 inline mr-1" />
                                    Select 2-5 patients to generate a comparative analysis
                                </p>
                            </div>
                        )}

                        {/* Patient List */}
                        <div className="space-y-2 max-h-[400px] overflow-y-auto">
                            {patients.length === 0 ? (
                                <div className="text-center py-12 text-gray-500">
                                    <Users className="h-12 w-12 mx-auto mb-2 text-gray-300" />
                                    <p className="font-medium">No patients available</p>
                                    <p className="text-sm mt-1">Upload documents to see patients</p>
                                </div>
                            ) : (
                                patients.map((patient) => (
                                    <button
                                        key={patient.id}
                                        onClick={() => handlePatientSelection(patient.id)}
                                        className={`w-full p-4 rounded-xl border-2 transition-all text-left medical-card-hover ${selectedPatients.includes(patient.id)
                                            ? 'border-teal-500 bg-teal-50'
                                            : 'border-transparent hover:border-teal-200'
                                            }`}
                                    >
                                        <div className="flex items-center justify-between">
                                            <div className="flex items-center space-x-3">
                                                <div className={`w-10 h-10 rounded-xl flex items-center justify-center font-bold ${selectedPatients.includes(patient.id)
                                                    ? 'bg-teal-500 text-white'
                                                    : 'bg-gradient-to-br from-teal-500 to-teal-600 text-white'
                                                    }`}>
                                                    {patient.name ? patient.name.charAt(0).toUpperCase() : 'U'}
                                                </div>
                                                <div>
                                                    <p className="font-semibold text-gray-900">{patient.name || 'Unknown'}</p>
                                                    <p className="text-sm text-gray-500">{patient.id}</p>
                                                </div>
                                            </div>
                                            {selectedPatients.includes(patient.id) && (
                                                <CheckCircle2 className="h-5 w-5 text-teal-500" />
                                            )}
                                        </div>
                                        <div className="mt-2 flex items-center space-x-4 text-xs text-gray-500">
                                            <span className="px-2 py-0.5 bg-teal-100 text-teal-700 rounded-full font-medium">{patient.document_count || 0} docs</span>
                                            {patient.age && <span>Age: {patient.age}</span>}
                                            {patient.gender && <span>{patient.gender}</span>}
                                        </div>
                                    </button>
                                ))
                            )}
                        </div>

                        {/* Action Button */}
                        <div className="mt-6">
                            <button
                                onClick={activeTab === 'summary' ? handleGenerateSummary : handleComparePatients}
                                disabled={loading || selectedPatients.length === 0 || (activeTab === 'compare' && selectedPatients.length < 2)}
                                className={`w-full py-3.5 px-6 rounded-xl font-bold transition-all flex items-center justify-center space-x-2 shadow-md ${loading || selectedPatients.length === 0 || (activeTab === 'compare' && selectedPatients.length < 2)
                                    ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                    : 'bg-teal-600 hover:bg-teal-700 text-white shadow-teal-500/30 hover:shadow-lg'
                                    }`}
                            >
                                {loading ? (
                                    <>
                                        <Loader2 className="h-5 w-5 animate-spin" />
                                        <span>Generating...</span>
                                    </>
                                ) : (
                                    <>
                                        <Sparkles className="h-5 w-5" />
                                        <span>
                                            {activeTab === 'summary' ? 'Generate Summary' : `Compare ${selectedPatients.length} Patients`}
                                        </span>
                                    </>
                                )}
                            </button>
                        </div>
                    </div>

                    {/* Right Panel - Results */}
                    <div className="medical-card p-6">
                        <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center">
                            <div className="w-8 h-8 bg-teal-100 rounded-lg flex items-center justify-center mr-2">
                                <FileText className="h-4 w-4 text-teal-600" />
                            </div>
                            Results
                        </h2>

                        {error && (
                            <div className="p-4 bg-red-50 border border-red-200 rounded-xl flex items-start space-x-3">
                                <AlertCircle className="h-5 w-5 text-red-500 mt-0.5 flex-shrink-0" />
                                <div className="flex-1">
                                    <p className="text-sm font-semibold text-red-800">Error</p>
                                    <p className="text-sm text-red-600 mt-1">{error}</p>
                                </div>
                            </div>
                        )}

                        {!result && !error && !loading && (
                            <div className="text-center py-16 text-gray-400">
                                <FileText className="h-16 w-16 mx-auto mb-4 text-gray-300" />
                                <p className="text-lg font-semibold text-gray-500">No results yet</p>
                                <p className="text-sm mt-2">Select patient(s) and generate {activeTab === 'summary' ? 'a summary' : 'a comparison'}</p>
                            </div>
                        )}

                        {loading && (
                            <div className="text-center py-16">
                                <Loader2 className="h-16 w-16 mx-auto mb-4 text-teal-500 animate-spin" />
                                <p className="text-lg font-semibold text-gray-700">Analyzing patient data...</p>
                                <p className="text-sm text-gray-500 mt-2">This may take a few moments</p>
                            </div>
                        )}

                        {result && (
                            <div className="space-y-4">
                                {/* Success Header */}
                                <div className="p-4 bg-green-50 border border-green-200 rounded-xl flex items-center space-x-3">
                                    <CheckCircle2 className="h-5 w-5 text-green-500" />
                                    <p className="text-sm font-semibold text-green-800">
                                        {activeTab === 'summary' ? 'Summary' : 'Comparison'} generated successfully
                                    </p>
                                </div>

                                {/* Result Content */}
                                <div className="space-y-4">
                                    <div className="p-5 bg-teal-50 rounded-xl border border-teal-100">
                                        <h3 className="text-lg font-bold text-teal-900 mb-3 flex items-center">
                                            <Sparkles className="h-5 w-5 mr-2" />
                                            {activeTab === 'summary' ? 'Patient Summary' : 'Comparative Analysis'}
                                        </h3>
                                        <div className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">
                                            {result.synthesis_text || result.summary || result.comparison || 'No content available'}
                                        </div>
                                    </div>

                                    {/* Key Findings */}
                                    {result.key_findings && (
                                        <div className="p-5 bg-blue-50 rounded-xl border border-blue-200">
                                            <h4 className="text-md font-bold text-blue-800 mb-2 flex items-center">
                                                <FileText className="h-4 w-4 mr-2" />
                                                Key Findings
                                            </h4>
                                            <pre className="text-xs text-blue-700 whitespace-pre-wrap font-mono">
                                                {JSON.stringify(result.key_findings, null, 2)}
                                            </pre>
                                        </div>
                                    )}

                                    {/* Report ID */}
                                    {result.report_id && (
                                        <div className="text-xs text-gray-500 bg-gray-50 rounded-lg p-3 border border-gray-200">
                                            <span className="font-semibold">Report ID:</span> {result.report_id}
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}
